-- 코드를 입력하세요
-- BOOK(BOOK_ID,CATEGORY,AUTHOR_ID,PRICE,PUBLISHED_DATE)
-- AUTHOR(AUTHOR_ID,AUTHOR_NAME)
-- BOOK_SALES (BOOK_ID,SALES_DATE,SALES)
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD') BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
