-- ONLINE_SALE(ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT,SALES_DATE)

-- 코드를 입력하세요
SELECT S.USER_ID, S.PRODUCT_ID
FROM ONLINE_SALE  S
GROUP BY S.USER_ID, S.PRODUCT_ID
HAVING COUNT(1) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC