-- 코드를 입력하세요
-- ONLINE_SALE (ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
-- OFFLINE_SALE (OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE)
-- 동일한 날짜, 상품 ID 유일
SELECT *
FROM (
    SELECT TO_CHAR(N.SALES_DATE,'YYYY-MM-DD') SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
    FROM ONLINE_SALE N
    WHERE TO_CHAR(N.SALES_DATE,'YYYY-MM-DD') LIKE '2022-03-%'
UNION ALL
    SELECT TO_CHAR(F.SALES_DATE,'YYYY-MM-DD') SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT
    FROM OFFLINE_SALE F
    WHERE TO_CHAR(F.SALES_DATE,'YYYY-MM-DD') LIKE '2022-03-%'
)
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC