-- 코드를 입력하세요
-- CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS)
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY (HISTORY_ID, CAR_ID, START_DATE, END_DATE)
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN (PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE)
SELECT * FROM (
SELECT 
A.CAR_ID,
A.CAR_TYPE,
A.DAILY_FEE * 30 * ((100-B.DISCOUNT_RATE)/100) AS FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE IN ('세단', 'SUV')) A,
(SELECT CAR_TYPE, DISCOUNT_RATE
 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE DURATION_TYPE = '30일 이상') B
WHERE A.CAR_TYPE = B.CAR_TYPE 
AND CAR_ID NOT IN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= DATE '2022-11-30' AND END_DATE >= DATE '2022-11-1'
)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
)
WHERE FEE >= 500000 AND FEE < 2000000