-- 코드를 입력하세요
-- CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS)
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY (HISTORY_ID, CAR_ID, START_DATE, END_DATE)
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN (PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE)
-- SELECT * FROM CAR_RENTAL_COMPANY_CAR
-- WHERE CAR_ID NOT IN (
--     SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--     WHERE END_DATE >= DATE '2022-11-01' AND START_DATE <= DATE '2022-11-30'
-- )
SELECT 
C.CAR_ID,
C.CAR_TYPE,
(C.DAILY_FEE * (1-(P.DISCOUNT_RATE/100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = '30일 이상'
AND C.CAR_TYPE IN ('SUV','세단')
AND (C.DAILY_FEE * (1-(P.DISCOUNT_RATE/100)) * 30)  >= 500000
AND (C.DAILY_FEE * (1-(P.DISCOUNT_RATE/100)) * 30) < 2000000
AND C.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= DATE '2022-11-01' AND START_DATE <= DATE '2022-11-30'
)
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;
