-- 코드를 입력하세요
-- ANIMAL_INS (ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE)
SELECT ANIMAL_TYPE, 
    CASE
        WHEN NAME IS NULL THEN 'No name'
        ELSE NAME
        END NAME
    ,SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;
