-- 코드를 입력하세요
-- REST_INFO(REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES, PARKING_LOT, ADDRESS, TEL)
-- REST_REVIEW(REVIEW_ID, REST_ID, MEMBER_ID, REVIEW_SCORE, REVIEW_TEXT,REVIEW_DATE)
SELECT
I.REST_ID,
I.REST_NAME,
I.FOOD_TYPE,
I.FAVORITES,
I.ADDRESS,
ROUND(AVG(R.REVIEW_SCORE), 2) SCORE

FROM REST_INFO I
INNER JOIN REST_REVIEW R
ON  I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY 
I.REST_ID,
I.REST_NAME,
I.FOOD_TYPE,
I.FAVORITES,
I.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC