-- 코드를 입력하세요
-- FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE)
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
)