WITH TOTAL_MEMBER AS (
    SELECT COUNT(*) AS CNT_MEMBER
    FROM USER_INFO
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)
SELECT
    TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR,
    TRUNC(TO_CHAR(S.SALES_DATE, 'MM'))   AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / T.CNT_MEMBER, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U
  ON S.USER_ID = U.USER_ID
JOIN TOTAL_MEMBER T
  ON 1=1
WHERE TO_CHAR(U.JOINED, 'YYYY') = '2021'
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM'), T.CNT_MEMBER
ORDER BY YEAR, MONTH;
