-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE*SUM(FO.AMOUNT)) AS PRICE
FROM FOOD_PRODUCT FP
    LEFT JOIN FOOD_ORDER FO
        ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE,"%Y-%m-%d") BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY FP.PRODUCT_ID
ORDER BY 
    PRICE DESC, 
    FP.PRODUCT_ID ASC
