-- 코드를 입력하세요
-- FOOD_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE)
-- FOOD_ORDER (ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, IN_DATE, OUT_DATE, FACTORY_ID, WAREHOUSE_ID)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.AMOUNT*P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(O.PRODUCE_DATE,'YYYYMM') = '202205'
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC