-- 코드를 입력하세요
-- FIRST_HALF (SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
-- JULY(SHIPMENT_ID,FLAVOR,	TOTAL_ORDER)
SELECT FLAVOR
FROM (SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
UNION ALL
    SELECT FLAVOR, TOTAL_ORDER
    FROM JULY)
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY