SELECT MEMBER_ID,
MEMBER_NAME,
GENDER,
substr(DATE_OF_BIRTH,1,10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND TLNO IS NOT NULL AND substr(DATE_OF_BIRTH,6,7) = 03
ORDER BY MEMBER_ID ASC