-- 코드를 입력하세요
WITH RM AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1
)


SELECT 
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") REVIEW_DATE
FROM REST_REVIEW R
    JOIN MEMBER_PROFILE M
        ON R.MEMBER_ID = M.MEMBER_ID
    JOIN RM RM
        ON R.MEMBER_ID = RM.MEMBER_ID

ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC