-- 코드를 입력하세요
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY(HISTORY_ID, CAR_ID, START_DATE, END_DATE)
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(1) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(1) >= 5
)
AND START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
HAVING COUNT(1) >= 1
ORDER BY MONTH ASC, CAR_ID DESC