-- 코드를 입력하세요
WITH MAX_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
RIGHT JOIN MAX_PRICE M ON F.PRICE = M.MAX_PRICE AND F.CATEGORY = M.CATEGORY
ORDER BY MAX_PRICE DESC